package content

var screenDefinitions = map[string]ScreenDefinition{
	"after_gen_free": screen("after_gen_free", "🎉 Готово! Вот твоя нейрофотосессия:",
		callback("free_gen", "free_gen", "✨ Ещё одно фото", "primary", 0, 0),
		callback("tariffs", "tariffs", "🚀 Активировать все функции", "positive", 1, 0),
		callback("back", "back", "◀️ Назад", "secondary", 2, 0),
	),
	"after_gen_paid": screen("after_gen_paid", "🎉 Готово!\n\n🤖 Модель: {{.ModelName}}\n🔧 Качество: {{.Resolution}}\n📐 Формат: {{.AspectRatio}}",
		openLink("download_photo", "download_photo", "⬇️ Скачать фото", 0, 0),
		callback("edit_result", "edit_result", "✏️ Изменить фото", "secondary", 1, 0),
		callback("gen_again", "gen_again", "✨ Сгенерировать еще", "primary", 2, 0),
		callback("back", "back", "◀️ Назад", "secondary", 3, 0),
	),
	"categories_empty": screen("categories_empty", "Категории пока не добавлены.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"bottom_menu": replyScreen("bottom_menu", "Быстрое меню",
		textButton("bottom_main_menu", "main_menu", "🏠 Главное меню", "secondary", 0, 0),
		textButton("bottom_buy_gens", "buy_gens", "💎 Купить генерации", "primary", 0, 1),
		textButton("bottom_settings", "settings", "⚙️ Настройки", "secondary", 1, 0),
		textButton("bottom_support", "support", "🆘 Техподдержка", "secondary", 1, 1),
		textButton("bottom_examples", "examples", "🖼 Примеры работ", "secondary", 1, 2),
	),
	"couple_intro": screen("couple_intro", "👫 Парные и семейные фото\n\nОтправь фото двух людей для создания совместной нейрофотосессии:",
		callback("back", "back", "◀️ Назад", "secondary", 100, 0),
	),
	"custom_prompt_intro": screen("custom_prompt_intro", "✍️ Опиши желаемый стиль фотосессии своими словами.\n\nПример: «деловой костюм на фоне небоскрёбов, профессиональное освещение»\n\nВведи описание:",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"edit_photo_intro": screen("edit_photo_intro", "✏️ Изменить фото\n\nОтправь фото которое хочешь изменить, и опиши что нужно сделать:",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"edit_result_missing_photo": screen("edit_result_missing_photo", "❌ Фото не найдено. Начни новую генерацию.",
		callback("main_menu", "main_menu", "🖼 Главное меню", "primary", 0, 0),
	),
	"edit_result_prompt": screen("edit_result_prompt", "✏️ Опиши, что нужно изменить на фото:",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"examples_collage": screen("examples_collage", "🌟 Примеры наших работ",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"generation_error": screen("generation_error", "❌ Произошла ошибка. Попробуй позже.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"generation_start_error": screen("generation_start_error", "❌ Ошибка запуска генерации. Попробуй позже.",
		callback("main_menu", "main_menu", "🖼 Главное меню", "primary", 0, 0),
	),
	"gender_select": screen("gender_select", "👤 Выбери свой пол — это поможет подобрать подходящие стили:",
		callback("gender_male", "gender_male", "👨 Мужской", "primary", 0, 0),
		callback("gender_female", "gender_female", "👩 Женский", "primary", 0, 1),
	),
	"generating_wait": screen("generating_wait", "⏳ Генерирую твоё фото...\n\nОбычно это занимает 1–2 минуты. Пожалуйста, подожди!"),
	"main_menu": screen("main_menu", "🎨 Главное меню\n\nВыбери что хочешь сделать:",
		callback("ready_prompts", "ready_prompts", "🖼 Готовые промты", "primary", 0, 0),
		callback("custom_prompt", "custom_prompt", "✍️ Свой промт", "primary", 1, 0),
		callback("edit_photo", "edit_photo", "✏️ Изменить фото", "primary", 2, 0),
		callback("couple", "couple", "👫 Парное фото", "primary", 3, 0),
		callback("saved_photo", "saved_photo", "💾 Запомнить фото", "secondary", 4, 0),
		callback("settings", "settings", "⚙️ Настройки", "secondary", 5, 0),
	),
	"no_gens_left": screen("no_gens_left", "😔 У тебя закончились генерации.\n\nПополни баланс для продолжения!",
		callback("tariffs", "tariffs", "💳 Выбрать тариф", "primary", 0, 0),
		callback("back", "back", "◀️ Назад", "secondary", 1, 0),
	),
	"payment_checkout": screen("payment_checkout", "💳 {{.TariffName}}\n{{.Description}}\n\nСумма: {{.Price}}\n\nДля оплаты перейди по ссылке ниже:",
		openLink("payment_url", "payment_url", "💳 Перейти к оплате", 0, 0),
		callback("back", "back", "◀️ Назад", "secondary", 1, 0),
	),
	"payment_invalid_tariff": screen("payment_invalid_tariff", "Неверный тариф.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"payment_link_error": screen("payment_link_error", "Не удалось создать ссылку на оплату. Попробуй позже.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"payment_order_error": screen("payment_order_error", "Ошибка создания заказа. Попробуй позже.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"payment_success": screen("payment_success", "🎉 Оплата прошла успешно!\n\nДобро пожаловать в мир нейрофотосессий! Твои генерации зачислены.",
		callback("main_menu", "main_menu", "🎨 Начать генерацию", "primary", 0, 0),
	),
	"payment_tariff_not_found": screen("payment_tariff_not_found", "Тариф не найден.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"payment_unavailable": screen("payment_unavailable", "Тарифы временно недоступны. Попробуй позже.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"photo_requirements": screen("photo_requirements", "📸 Отлично! Теперь загрузи своё фото.\n\n✅ Требования к фото:\n• Лицо должно быть хорошо видно\n• Хорошее освещение\n• Без очков и головных уборов\n• Один человек на фото\n\nОтправь фото прямо в чат:",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"prompt_not_found": screen("prompt_not_found", "Шаблон не найден.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"prompts_empty": screen("prompts_empty", "В этой категории пока нет шаблонов.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"prompts_list": screen("prompts_list", "Выбери стиль:",
		callback("back", "back", "◀️ Назад", "secondary", 100, 0),
	),
	"ready_prompts_intro": screen("ready_prompts_intro", "🖼 Готовые стили\n\nВыбери категорию:",
		callback("back", "back", "◀️ Назад", "secondary", 100, 0),
	),
	"referral_bonus_awarded": screen("referral_bonus_awarded", "🎁 Твой реферал оплатил генерации! +2 бесплатные генерации.",
		callback("main_menu", "main_menu", "🖼 Главное меню", "primary", 0, 0),
	),
	"referral_status": screen("referral_status", "🎁 Реферальная программа\n\nТы пригласил уже {{.Count}} человек.\n\nЗа каждого пользователя, который оплатит любое количество генераций, ты получишь 2 бесплатные генерации!\n\nТвоя ссылка:\n{{.RefLink}}",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"saved_photo_empty": screen("saved_photo_empty", "💾 Раздел «Запомнить фото»\n\nЗагрузите базовое фото — оно будет автоматически использоваться в готовых промптах и парных фото:",
		callback("saved_photo_upload", "saved_photo_upload", "📤 Загрузить фото", "primary", 0, 0),
		callback("back", "back", "◀️ Назад", "secondary", 1, 0),
	),
	"saved_photo_error": screen("saved_photo_error", "❌ Ошибка сохранения. Попробуй позже.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"saved_photo_filled": screen("saved_photo_filled", "💾 Ваше сохранённое фото\n🔄 Использование в готовых промптах: {{.Status}}",
		callback("saved_photo_replace", "saved_photo_upload", "✏️ Заменить фото", "secondary", 0, 0),
		toggle("saved_photo_toggle", "toggle_saved_photo", "▶️ Включить в готовых промптах", "⏸ Выключить в готовых промптах", "primary", 1, 0),
		callback("back", "back", "◀️ Назад", "secondary", 2, 0),
	),
	"saved_photo_generation_wait": screen("saved_photo_generation_wait", "⏳ Начинаю генерацию...\n📋 Шаблон: {{.PromptName}}\n📸 Используется ваше сохранённое фото"),
	"saved_photo_saved": screen("saved_photo_saved", "✅ Фото сохранено!\n🔄 Использование в готовых промптах: {{.Status}}",
		callback("saved_photo_replace", "saved_photo_upload", "✏️ Заменить фото", "secondary", 0, 0),
		toggle("saved_photo_toggle", "toggle_saved_photo", "▶️ Включить в готовых промптах", "⏸ Выключить в готовых промптах", "primary", 1, 0),
		callback("back", "back", "◀️ Назад", "secondary", 2, 0),
	),
	"saved_photo_upload_prompt": screen("saved_photo_upload_prompt", "📤 Отправьте фото — оно сохранится и будет использоваться по умолчанию:",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"settings_balance": screen("settings_balance", "💳 Баланс\n\n🔹 Бесплатных: {{.FreeGens}}\n🔸 Платных: {{.PaidGens}}\n\nПополнить баланс:",
		callback("back", "back", "◀️ Назад", "secondary", 100, 0),
	),
	"settings_format": screen("settings_format", "📐 Выбери формат изображения:",
		selectButton("ar_1_1", "ar_1_1", "1:1 (Квадрат)", "primary", "1:1", 0, 0),
		selectButton("ar_9_16", "ar_9_16", "9:16 (Портрет)", "primary", "9:16", 1, 0),
		selectButton("ar_16_9", "ar_16_9", "16:9 (Пейзаж)", "primary", "16:9", 2, 0),
		callback("settings", "settings", "◀️ Назад", "secondary", 3, 0),
	),
	"settings_model": screen("settings_model", "🤖 Выбери модель генерации:",
		selectButton("model_nbp", "model_nbp", "Nano Banana Pro", "primary", "google/nano-banana-pro", 0, 0),
		selectButton("model_nb2", "model_nb2", "Nano Banana 2", "primary", "google/nano-banana-2", 1, 0),
		selectButton("model_gpt2", "model_gpt2", "GPT Image 2", "primary", "openai/gpt-image-2", 2, 0),
		callback("settings", "settings", "◀️ Назад", "secondary", 3, 0),
	),
	"settings_overview": screen("settings_overview", "⚙️ Настройки\n\n🎯 Баланс генераций: {{.TotalGens}}\n🤖 Модель: {{.ModelName}}\n🔧 Качество: {{.Resolution}}\n📐 Формат: {{.AspectRatio}}",
		callback("quality", "quality", "🔧 Качество", "primary", 0, 0),
		callback("format", "format", "📐 Формат", "primary", 1, 0),
		callback("balance", "balance", "💳 Баланс", "primary", 2, 0),
		callback("model", "model", "🤖 Модель", "primary", 3, 0),
		callback("back", "back", "◀️ Назад", "secondary", 4, 0),
	),
	"settings_quality": screen("settings_quality", "🔧 Выбери качество генерации:",
		selectButton("quality_1k", "quality_1k", "Стандарт (1k)", "primary", "1k", 0, 0),
		selectButton("quality_2k", "quality_2k", "HD (2k)", "primary", "2k", 1, 0),
		selectButton("quality_4k", "quality_4k", "Ультра (4k)", "primary", "4k", 2, 0),
		callback("settings", "settings", "◀️ Назад", "secondary", 3, 0),
	),
	"subscribe_cta": screen("subscribe_cta", "📌 Подпишись на нашу группу и возвращайся!\n\nПосле подписки нажми кнопку «Я подписался»",
		openLink("subscribe_group", "subscribe_group", "📌 Подписаться на группу", 0, 0),
		callback("check_sub", "check_sub", "✅ Я подписался", "positive", 1, 0),
		callback("back", "back", "◀️ Назад", "secondary", 2, 0),
	),
	"support_text": screen("support_text", "📞 Техподдержка\n\nЕсли у вас возникли вопросы или проблемы — напишите нам:\n@support_username",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"tariffs": screen("tariffs", "💳 Выбери тариф для продолжения:",
		callback("back", "back", "◀️ Назад", "secondary", 100, 0),
	),
	"unknown_command": screen("unknown_command", "Неизвестная команда. Возвращаю в главное меню.",
		callback("main_menu", "main_menu", "🖼 Главное меню", "primary", 0, 0),
	),
	"welcome": screen("welcome", "👋 Привет! Я бот для создания нейрофотосессий.\n\nЯ превращу твои фото в профессиональные снимки с помощью AI.\n\nГотов попробовать?",
		callback("free_gen", "free_gen", "✨ Попробовать бесплатно", "positive", 0, 0),
		callback("referral", "referral", "🎁 Реферальная программа", "secondary", 1, 0),
	),
	"worker_generation_failed": screen("worker_generation_failed", "❌ Генерация завершилась с ошибкой. Попробуй позже."),
	"worker_no_output":         screen("worker_no_output", "❌ Не удалось получить результат."),
	"worker_submit_error":      screen("worker_submit_error", "❌ Ошибка при запуске генерации. Попробуй ещё раз."),
	"worker_vk_upload_error":   screen("worker_vk_upload_error", "❌ Фото сгенерировано, но не удалось загрузить в VK. Генерация возвращена на твой баланс."),
}

func screen(key, text string, items ...Button) ScreenDefinition {
	return ScreenDefinition{
		Key:         key,
		DefaultText: text,
		Keyboard: Keyboard{
			Inline: true,
			Items:  items,
		},
	}
}

func replyScreen(key, text string, items ...Button) ScreenDefinition {
	return ScreenDefinition{
		Key:         key,
		DefaultText: text,
		Keyboard: Keyboard{
			Inline:  false,
			OneTime: false,
			Items:   items,
		},
	}
}

func callback(slotID, actionKey, label, color string, row, position int) Button {
	return Button{
		SlotID:    slotID,
		ActionKey: actionKey,
		Kind:      ButtonKindCallback,
		Label:     label,
		Row:       row,
		Position:  position,
		Visible:   true,
		Color:     color,
	}
}

func textButton(slotID, actionKey, label, color string, row, position int) Button {
	return Button{
		SlotID:    slotID,
		ActionKey: actionKey,
		Kind:      ButtonKindText,
		Label:     label,
		Row:       row,
		Position:  position,
		Visible:   true,
		Color:     color,
	}
}

func openLink(slotID, binding, label string, row, position int) Button {
	return Button{
		SlotID:      slotID,
		ActionKey:   binding,
		Kind:        ButtonKindOpenLink,
		Label:       label,
		Row:         row,
		Position:    position,
		Visible:     true,
		LinkBinding: binding,
	}
}

func selectButton(slotID, actionKey, label, color, value string, row, position int) Button {
	return Button{
		SlotID:    slotID,
		ActionKey: actionKey,
		Kind:      ButtonKindSelect,
		Label:     label,
		Row:       row,
		Position:  position,
		Visible:   true,
		Color:     color,
		Value:     value,
	}
}

func toggle(slotID, actionKey, labelOff, labelOn, color string, row, position int) Button {
	return Button{
		SlotID:    slotID,
		ActionKey: actionKey,
		Kind:      ButtonKindToggle,
		Label:     labelOff,
		LabelOn:   labelOn,
		Row:       row,
		Position:  position,
		Visible:   true,
		Color:     color,
	}
}
