package content

var screenDefinitions = map[string]ScreenDefinition{
	"after_gen_free": screen("after_gen_free", "🎉 Готово! Вот твоя нейрофотосессия:",
		callback("free_gen", "free_gen", "✨ Ещё одно фото", "primary", 0, 0),
		callback("tariffs", "tariffs", "🚀 Активировать все функции", "positive", 1, 0),
		callback("back", "back", "◀️ Назад", "secondary", 2, 0),
	),
	"after_gen_paid": screen("after_gen_paid", "🎉 Готово!\n\n🤖 Модель: {{.ModelName}}\n🔧 Качество: {{.Resolution}}\n📐 Формат: {{.AspectRatio}}",
		openLink("download_photo", "download_photo", "⬇️ Скачать фото", 0, 0),
		callback("edit_result", "edit_result", "✏️ Изменить фото", "secondary", 1, 0),
		callback("gen_again", "gen_again", "✨ Сгенерировать еще", "primary", 2, 0),
		callback("back", "back", "◀️ Назад", "secondary", 3, 0),
	),
	"broadcast_no_gens": screen("broadcast_no_gens", "😔 У вас осталось 0 генераций.\n\nЧтобы сделать такие же фото, пополните баланс:"),
	"categories_empty":  screen("categories_empty", "Категории пока не добавлены.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"bottom_menu": replyScreen("bottom_menu", "Быстрое меню",
		textButton("bottom_main_menu", "main_menu", "🏠 Главное меню", "secondary", 0, 0),
		textButton("bottom_buy_gens", "buy_gens", "💎 Купить генерации", "primary", 0, 1),
		textButton("bottom_settings", "settings", "👤 Мой профиль", "secondary", 1, 0),
		textButton("bottom_support", "support", "🆘 Техподдержка", "secondary", 1, 1),
		textButton("bottom_examples", "examples", "🖼 Примеры работ", "secondary", 1, 2),
	),
	"couple_intro": screen("couple_intro", "👫 Парные и семейные фото\n\nОтправь от 1 до 6 фото пары или семьи одним сообщением (можно одно совместное фото) для создания совместной нейрофотосессии.\n\nКак только фото будут загружены, я покажу категории стилей:",
		callback("back", "back", "◀️ Назад", "secondary", 100, 0),
	),
	"couple_categories": screen("couple_categories", "✅ Фото загружены!\n\n👫 Теперь выбери категорию совместной фотосессии:",
		callback("back", "back", "🏠 В меню", "secondary", 100, 0),
	),
	"couple_submenu": screen("couple_submenu", "✅ Фото загружены!\n\n👫 Выбери тип съёмки:",
		callback("back", "back", "🏠 В меню", "secondary", 100, 0),
	),
	"custom_prompt_intro": screen("custom_prompt_intro", "✍️ Опиши желаемый стиль фотосессии своими словами.\n\nПример: «деловой костюм на фоне небоскрёбов, профессиональное освещение»\n\nМожно сразу одним сообщением отправить описание и от 1 до 6 фото.\n\nВведи описание:",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"edit_photo_intro": screen("edit_photo_intro", "✏️ Изменить фото\n\nОтправь от 1 до 6 фото одним сообщением, которые хочешь изменить. Можно сразу в этом же сообщении добавить описание правок, либо бот спросит его следом:",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"edit_result_missing_photo": screen("edit_result_missing_photo", "❌ Фото не найдено. Начни новую генерацию.",
		callback("main_menu", "main_menu", "🖼 Главное меню", "primary", 0, 0),
	),
	"edit_result_prompt": screen("edit_result_prompt", "✏️ Опиши, что нужно изменить на фото:",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"free_gen_prompt": screen("free_gen_prompt", "professional portrait photo of a {{.GenderLabel}}, studio lighting, high quality, photorealistic"),
	"examples_collage": screen("examples_collage", "🌟 Примеры наших работ\n\nВыбери, что хочешь посмотреть:",
		// У inline-клавиатуры ВК не больше 6 строк, а кнопок здесь семь. Длинные
		// названия держим по одной в строке, а короткие «Разное» и «Назад»
		// ставим в общий последний ряд — так ничего не обрезается.
		callback("examples_self", "examples_self", "🙋 Фото для себя", "primary", 0, 0),
		callback("examples_couple", "examples_couple", "👫 Парные фото", "primary", 1, 0),
		callback("examples_kids", "examples_kids", "🧒 Детские фото", "primary", 2, 0),
		callback("examples_edit", "examples_edit", "✏️ Изменение фото", "primary", 3, 0),
		callback("examples_greetings", "examples_greetings", "🎉 Поздравления", "primary", 4, 0),
		callback("examples_misc", "examples_misc", "🎨 Разное", "primary", 5, 0),
		callback("back", "back", "◀️ Назад", "secondary", 5, 1),
	),
	"examples_self":      exampleCategoryScreen("examples_self", "🙋 Фото для себя\n\nПортреты в разных стилях: деловые, атмосферные, для соцсетей и резюме.\n\nТакие же сделаем с твоим лицом — нужно только загрузить фото."),
	"examples_couple":    exampleCategoryScreen("examples_couple", "👫 Парные фото\n\nСовместные фотосессии для пары или всей семьи: от студийных портретов до атмосферных прогулок.\n\nЗагрузи ваши фото — и получишь такие же кадры."),
	"examples_kids":      exampleCategoryScreen("examples_kids", "🧒 Детские фото\n\nСказочные и праздничные сюжеты, детские портреты в любимых образах.\n\nОдно фото ребёнка — и готова целая фотосессия."),
	"examples_edit":      exampleCategoryScreen("examples_edit", "✏️ Изменение фото\n\nМеняем фон, одежду, причёску, убираем лишнее — фото остаётся твоим, меняются только детали.\n\nОпиши правку словами, остальное сделает нейросеть."),
	"examples_greetings": exampleCategoryScreen("examples_greetings", "🎉 Поздравления\n\nПерсональные открытки к дню рождения, 8 марта, Новому году и любому празднику — с лицом того, кого поздравляешь.\n\nОтличный подарок за пару минут."),
	"examples_misc":      exampleCategoryScreen("examples_misc", "🎨 Разное\n\nВсё остальное: аватарки, мемы, обложки, фантазийные образы и любые идеи из головы.\n\nОпиши задумку — соберём кадр под неё."),
	"generation_error": screen("generation_error", "❌ Произошла ошибка. Попробуй позже.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"generation_start_error": screen("generation_start_error", "❌ Ошибка запуска генерации. Попробуй позже.",
		callback("main_menu", "main_menu", "🖼 Главное меню", "primary", 0, 0),
	),
	"gender_select": screen("gender_select", "👤 Выбери свой пол — это поможет подобрать подходящие стили:",
		callback("gender_male", "gender_male", "👨 Мужской", "primary", 0, 0),
		callback("gender_female", "gender_female", "👩 Женский", "primary", 0, 1),
	),
	"generating_wait": screen("generating_wait", "⏳ Генерирую твоё фото...\n\nОбычно это занимает 1–2 минуты. Пожалуйста, подожди!"),
	"kids_intro": screen("kids_intro", "👶 Детские фото\n\nСказочные и праздничные образы для ребёнка.\n\nВыбери, для кого делаем фотосессию:",
		callback("back", "back", "🏠 В меню", "secondary", 100, 0),
	),
	"greetings_intro": screen("greetings_intro", "🎉 Поздравления\n\nПерсональная открытка с лицом того, кого поздравляешь.\n\nКого поздравляем?",
		callback("back", "back", "🏠 В меню", "secondary", 100, 0),
	),
	"greetings_holidays": screen("greetings_holidays", "🎊 С каким праздником поздравляем?",
		callback("back", "back", "◀️ Назад", "secondary", 100, 0),
	),
	"main_menu": screen("main_menu", "🎨 Главное меню\n\nВыбери что хочешь сделать:",
		callback("ready_prompts", "ready_prompts", "🖼 Готовые промты", "primary", 0, 0),
		// Семь кнопок при лимите ВК в шесть строк. Две работы «со своим фото»
		// сведены в общий ряд: названия короткие и не обрежутся, а разделы-
		// фотосессии остаются по одной кнопке в ряд.
		callback("custom_prompt", "custom_prompt", "✍️ Свой промт", "primary", 1, 0),
		callback("edit_photo", "edit_photo", "✏️ Изменить фото", "primary", 1, 1),
		callback("couple", "couple", "👫 Парное фото", "primary", 3, 0),
		// Строка 50 — отдельный ряд даже на экранах, где в БД уже лежат строки
		// старых кнопок; positive выделяет новый раздел среди primary.
		callback("kids", "kids", "👶 Детские фото", "positive", 50, 0),
		callback("greetings", "greetings", "🎉 Поздравления", "positive", 51, 0),
		callback("trends", "trends", "🔥 Тренды", "positive", 52, 0),
	),
	"no_gens_left": screen("no_gens_left", "😔 У тебя закончились генерации.\n\nПополни баланс для продолжения!",
		callback("tariffs", "tariffs", "💳 Выбрать тариф", "primary", 0, 0),
		callback("back", "back", "◀️ Назад", "secondary", 1, 0),
	),
	"payment_checkout": screen("payment_checkout", "💳 {{.TariffName}}\n{{.Description}}\n\nСумма: {{.Price}}\n\nДля оплаты перейди по ссылке ниже:",
		openLink("payment_url", "payment_url", "💳 Перейти к оплате", 0, 0),
		callback("back", "back", "◀️ Назад", "secondary", 1, 0),
	),
	"payment_invalid_tariff": screen("payment_invalid_tariff", "Неверный тариф.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"payment_link_error": screen("payment_link_error", "Не удалось создать ссылку на оплату. Попробуй позже.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"payment_order_error": screen("payment_order_error", "Ошибка создания заказа. Попробуй позже.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"payment_canceled": screen("payment_canceled", "Оплата была отменена.\n\nЕсли хочешь, можешь выбрать тариф и попробовать снова.",
		callback("main_menu", "main_menu", "В главное меню", "primary", 0, 0),
	),
	"payment_reminder": screen("payment_reminder", "👀 Вижу, ты заглянул в тарифы, но так и не выбрал.\n\nМожно начать с малого — {{.GensCount}} генерации за {{.Price}}. Этого хватит, чтобы попробовать и понять, нравится ли результат."),
	"payment_success": screen("payment_success", "🎉 Оплата прошла успешно!\n\nЗачислено генераций: {{.GensCount}}\n\nДобро пожаловать в мир нейрофотосессий!",
		callback("main_menu", "main_menu", "🎨 Начать генерацию", "primary", 0, 0),
	),
	"payment_tariff_not_found": screen("payment_tariff_not_found", "Тариф не найден.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"payment_unavailable": screen("payment_unavailable", "Тарифы временно недоступны. Попробуй позже.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"photo_requirements": screen("photo_requirements", "📸 Отлично! Теперь загрузи фото.\n\n✅ Требования к фото:\n• Лицо должно быть хорошо видно\n• Хорошее освещение\n• Без очков и головных уборов\n• Для одиночных сценариев — один человек на каждом фото\n• Можно отправить от 1 до 6 фото одним сообщением\n\nОтправь фото прямо в чат:",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"prompt_not_found": screen("prompt_not_found", "Шаблон не найден.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"prompts_empty": screen("prompts_empty", "В этой категории пока нет шаблонов.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	// Один экран на все разделы: узел уже виден в меню, но промтов в нём ещё нет.
	// Раздел при этом остаётся кликабельным — заказчик наполняет его из админки.
	"section_soon": screen("section_soon", "⏳ Скоро здесь появятся новые стили.\n\nЗаглядывай позже — раздел уже готовится.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	// На списках с пагинацией внизу уже стоит «⬅️ Назад» листалки, поэтому
	// кнопка выхода называется «В меню» — иначе в одном ряду два «Назад».
	"prompts_list": screen("prompts_list", "Выбери стиль:",
		callback("back", "back", "🏠 В меню", "secondary", 100, 0),
	),
	"ready_prompts_intro": screen("ready_prompts_intro", "🖼 Готовые стили\n\nВыбери категорию:",
		callback("back", "back", "🏠 В меню", "secondary", 100, 0),
	),
	"trends_intro": screen("trends_intro", "🔥 Тренды\n\nСамые популярные образы этого сезона — то, что сейчас у всех в ленте.\n\nВыбери, что делаем:",
		callback("back", "back", "🏠 В меню", "secondary", 100, 0),
	),
	"referral_bonus_awarded": screen("referral_bonus_awarded", "🎁 Твой реферал оплатил генерации! +2 бесплатные генерации.",
		callback("main_menu", "main_menu", "🖼 Главное меню", "primary", 0, 0),
	),
	"referral_status": screen("referral_status", "🎁 Реферальная программа\n\nТы пригласил уже {{.Count}} человек.\n\nЗа каждого пользователя, который оплатит любое количество генераций, ты получишь 2 бесплатные генерации!\n\nТвоя ссылка:\n{{.RefLink}}",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"saved_photo_empty": screen("saved_photo_empty", "💾 Раздел «Запомнить фото»\n\nЗагрузите базовое фото — оно будет автоматически использоваться в готовых промптах и парных фото:",
		callback("saved_photo_upload", "saved_photo_upload", "📤 Загрузить фото", "primary", 0, 0),
		callback("back", "back", "◀️ Назад", "secondary", 1, 0),
	),
	"saved_photo_error": screen("saved_photo_error", "❌ Ошибка сохранения. Попробуй позже.",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"saved_photo_filled": screen("saved_photo_filled", "💾 Ваше сохранённое фото\n🔄 Использование в готовых промптах: {{.Status}}",
		callback("saved_photo_replace", "saved_photo_upload", "✏️ Заменить фото", "secondary", 0, 0),
		toggle("saved_photo_toggle", "toggle_saved_photo", "▶️ Включить в готовых промптах", "⏸ Выключить в готовых промптах", "primary", 1, 0),
		callback("back", "back", "◀️ Назад", "secondary", 2, 0),
	),
	"saved_photo_generation_wait": screen("saved_photo_generation_wait", "⏳ Начинаю генерацию...\n📋 Шаблон: {{.PromptName}}\n📸 Используется ваше сохранённое фото"),
	"saved_photo_saved": screen("saved_photo_saved", "✅ Фото сохранено!\n🔄 Использование в готовых промптах: {{.Status}}",
		callback("saved_photo_replace", "saved_photo_upload", "✏️ Заменить фото", "secondary", 0, 0),
		toggle("saved_photo_toggle", "toggle_saved_photo", "▶️ Включить в готовых промптах", "⏸ Выключить в готовых промптах", "primary", 1, 0),
		callback("back", "back", "◀️ Назад", "secondary", 2, 0),
	),
	"saved_photo_upload_prompt": screen("saved_photo_upload_prompt", "📤 Отправьте одно базовое фото — оно сохранится и будет использоваться по умолчанию:",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"saved_photo_batch_not_supported": screen("saved_photo_batch_not_supported", "ℹ️ В разделе «Запомнить фото» пока сохраняется только один базовый кадр.\n\nОтправь одно фото, а для генераций в остальных режимах можно по-прежнему отправлять до 6 фото одним сообщением:",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"settings_balance": screen("settings_balance", "💳 Баланс\n\n🎯 Доступно генераций: {{.TotalGens}}\n\nПополнить баланс:",
		callback("back", "back", "◀️ Назад", "secondary", 100, 0),
	),
	"settings_format": screen("settings_format", "📐 Выбери формат изображения:",
		selectButton("ar_1_1", "ar_1_1", "1:1 (Квадрат)", "primary", "1:1", 0, 0),
		selectButton("ar_9_16", "ar_9_16", "9:16 (Портрет)", "primary", "9:16", 1, 0),
		selectButton("ar_16_9", "ar_16_9", "16:9 (Пейзаж)", "primary", "16:9", 2, 0),
		callback("settings", "settings", "◀️ Назад", "secondary", 3, 0),
	),
	"settings_model": screen("settings_model", "🤖 Выбери модель генерации:",
		selectButton("model_nbp", "model_nbp", "Nano Banana Pro", "primary", "google/nano-banana-pro", 0, 0),
		selectButton("model_nb2", "model_nb2", "Nano Banana 2", "primary", "google/nano-banana-2", 1, 0),
		selectButton("model_gpt2", "model_gpt2", "GPT Image 2", "primary", "openai/gpt-image-2", 2, 0),
		callback("settings", "settings", "◀️ Назад", "secondary", 3, 0),
	),
	// «Мой профиль» — единственная точка входа в личные настройки: из главного
	// меню кнопка убрана, живёт в нижнем постоянном меню. Сюда же переехало
	// «Запомнить фото». Ровно 6 строк — предел inline-клавиатуры ВК.
	"settings_overview": screen("settings_overview", "👤 Мой профиль\n\n🆔 ID: {{.VKID}}\n🎯 Баланс генераций: {{.TotalGens}}\n🤖 Модель: {{.ModelName}}\n🔧 Качество: {{.Resolution}}\n📐 Формат: {{.AspectRatio}}\n\n🎁 Приглашено рефералов: {{.ReferralCount}}{{if .ReferralLink}}\n🔗 Твоя ссылка:\n{{.ReferralLink}}{{end}}",
		callback("quality", "quality", "🔧 Качество", "primary", 0, 0),
		callback("format", "format", "📐 Формат", "primary", 1, 0),
		callback("balance", "balance", "💳 Баланс", "primary", 2, 0),
		callback("model", "model", "🤖 Модель", "primary", 3, 0),
		callback("saved_photo", "saved_photo", "💾 Запомнить фото", "secondary", 4, 0),
		callback("back", "back", "◀️ Назад", "secondary", 5, 0),
	),
	"settings_quality": screen("settings_quality", "🔧 Выбери качество генерации:",
		selectButton("quality_1k", "quality_1k", "Стандарт (1k)", "primary", "1k", 0, 0),
		selectButton("quality_2k", "quality_2k", "HD (2k)", "primary", "2k", 1, 0),
		selectButton("quality_4k", "quality_4k", "Ультра (4k)", "primary", "4k", 2, 0),
		callback("settings", "settings", "◀️ Назад", "secondary", 3, 0),
	),
	"subscribe_cta": screen("subscribe_cta", "📌 Подпишись на нашу группу и возвращайся!\n\nПосле подписки нажми кнопку «Я подписался»",
		openLink("subscribe_group", "subscribe_group", "📌 Подписаться на группу", 0, 0),
		callback("check_sub", "check_sub", "✅ Я подписался", "positive", 1, 0),
		callback("back", "back", "◀️ Назад", "secondary", 2, 0),
	),
	"support_text": screen("support_text", "📞 Техподдержка\n\nЕсли у вас возникли вопросы или проблемы — напишите нам:\n@support_username",
		callback("back", "back", "◀️ Назад", "secondary", 0, 0),
	),
	"tariffs": screen("tariffs", "💳 Выбери тариф для продолжения:",
		callback("examples", "examples", "🖼 Примеры работ", "positive", 50, 0),
		callback("back", "back", "◀️ Назад", "secondary", 100, 0),
	),
	"unknown_command": screen("unknown_command", "Неизвестная команда. Возвращаю в главное меню.",
		callback("main_menu", "main_menu", "🖼 Главное меню", "primary", 0, 0),
	),
	"welcome": screen("welcome", "👋 Привет! Я бот для создания нейрофотосессий.\n\nЯ превращу твои фото в профессиональные снимки с помощью AI.\n\nГотов попробовать?",
		callback("free_gen", "free_gen", "✨ Попробовать бесплатно", "positive", 0, 0),
		callback("referral", "referral", "🎁 Реферальная программа", "secondary", 1, 0),
		// Строка 50 — чтобы новая кнопка встала отдельным рядом даже на экранах,
		// у которых в БД уже сохранены строки старых кнопок.
		callback("examples", "examples", "🖼 Примеры работ", "positive", 50, 0),
	),
	// ─── Видео ───────────────────────────────────────────────────────────────
	"video_generating_wait": screen("video_generating_wait", "🎬 Делаю видео «{{.PromptName}}»\n\nЭто дольше фото: сначала собираю кадр, потом оживляю его. Обычно занимает 3–5 минут — я пришлю результат сам, ждать в чате не нужно.\n\nСписано генераций: {{.CostGens}}"),
	"video_scene_ready":     screen("video_scene_ready", "📸 Кадр собран, запускаю анимацию.\n\nОсталось пара минут."),
	"after_gen_video": screen("after_gen_video", "🎬 Готово! Твоё видео на {{.Duration}} секунд:",
		openLink("download_video", "download_video", "⬇️ Скачать видео", 0, 0),
		callback("trends", "trends", "🔥 Ещё тренды", "primary", 1, 0),
		callback("main_menu", "main_menu", "🏠 Главное меню", "secondary", 2, 0),
	),
	// Сцена не собралась — до видео-модели дело не дошло, поэтому и текст
	// отличается: пользователю важно знать, что дело в его фото, а не в сервисе.
	"video_scene_failed": screen("video_scene_failed", "❌ Не получилось собрать кадр для видео. Генерации возвращены на баланс.\n\nЧаще всего помогает фото покрупнее и без посторонних лиц — попробуй ещё раз.",
		callback("trends", "trends", "🔥 К трендам", "primary", 0, 0),
		callback("main_menu", "main_menu", "🏠 Главное меню", "secondary", 1, 0),
	),
	"video_generation_failed": screen("video_generation_failed", "❌ Видео не сгенерировалось. Генерации возвращены на баланс — попробуй ещё раз или выбери другой тренд.",
		callback("trends", "trends", "🔥 К трендам", "primary", 0, 0),
		callback("main_menu", "main_menu", "🏠 Главное меню", "secondary", 1, 0),
	),
	"no_gens_for_video": screen("no_gens_for_video", "🎬 Это видео стоит {{.CostGens}} генераций, а у тебя на балансе {{.UserGens}}.\n\nНе хватает: {{.MissingGens}}. Пополни баланс — и запустим.",
		callback("tariffs", "tariffs", "💳 Выбрать тариф", "primary", 0, 0),
		callback("back", "back", "◀️ Назад", "secondary", 1, 0),
	),
	"worker_generation_failed": screen("worker_generation_failed", "❌ Генерация завершилась с ошибкой. Попробуй позже."),
	"worker_no_output":         screen("worker_no_output", "❌ Не удалось получить результат."),
	"worker_submit_error":      screen("worker_submit_error", "❌ Ошибка при запуске генерации. Попробуй ещё раз."),
	"worker_vk_upload_error":   screen("worker_vk_upload_error", "❌ Фото сгенерировано, но не удалось загрузить в VK. Генерация возвращена на твой баланс."),
}

func screen(key, text string, items ...Button) ScreenDefinition {
	return ScreenDefinition{
		Key:         key,
		DefaultText: text,
		Keyboard: Keyboard{
			Inline: true,
			Items:  items,
		},
	}
}

// examplesPlaceholderImage — временный коллаж, пока заказчик не загрузил свои
// картинки для каждой категории в админке.
const examplesPlaceholderImage = "https://s3.ru1.storage.beget.cloud/bbd5f068f995-project/admin_uploads/1778658113_photo_2026-05-13_16-37-11.jpg"

// exampleCategoryScreen — экран одной категории примеров работ: картинка и текст
// задаются в админке, кнопки одинаковые для всех категорий.
func exampleCategoryScreen(key, text string) ScreenDefinition {
	def := screen(key, text,
		callback("tariffs", "tariffs", "🚀 Активировать все функции", "positive", 0, 0),
		callback("examples", "examples", "◀️ Назад", "secondary", 1, 0),
	)
	def.DefaultImageURL = examplesPlaceholderImage
	return def
}

func replyScreen(key, text string, items ...Button) ScreenDefinition {
	return ScreenDefinition{
		Key:         key,
		DefaultText: text,
		Keyboard: Keyboard{
			Inline:  false,
			OneTime: false,
			Items:   items,
		},
	}
}

func callback(slotID, actionKey, label, color string, row, position int) Button {
	return Button{
		SlotID:    slotID,
		ActionKey: actionKey,
		Kind:      ButtonKindCallback,
		Label:     label,
		Row:       row,
		Position:  position,
		Visible:   true,
		Color:     color,
	}
}

func textButton(slotID, actionKey, label, color string, row, position int) Button {
	return Button{
		SlotID:    slotID,
		ActionKey: actionKey,
		Kind:      ButtonKindText,
		Label:     label,
		Row:       row,
		Position:  position,
		Visible:   true,
		Color:     color,
	}
}

func openLink(slotID, binding, label string, row, position int) Button {
	return Button{
		SlotID:      slotID,
		ActionKey:   binding,
		Kind:        ButtonKindOpenLink,
		Label:       label,
		Row:         row,
		Position:    position,
		Visible:     true,
		LinkBinding: binding,
	}
}

func selectButton(slotID, actionKey, label, color, value string, row, position int) Button {
	return Button{
		SlotID:    slotID,
		ActionKey: actionKey,
		Kind:      ButtonKindSelect,
		Label:     label,
		Row:       row,
		Position:  position,
		Visible:   true,
		Color:     color,
		Value:     value,
	}
}

func toggle(slotID, actionKey, labelOff, labelOn, color string, row, position int) Button {
	return Button{
		SlotID:    slotID,
		ActionKey: actionKey,
		Kind:      ButtonKindToggle,
		Label:     labelOff,
		LabelOn:   labelOn,
		Row:       row,
		Position:  position,
		Visible:   true,
		Color:     color,
	}
}
